# Generated by Django 2.0.6 on 2018-06-27 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Close_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('trading_date', models.DateField()),
                ('buy_or_sell', models.CharField(max_length=100)),
                ('open_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('number', models.IntegerField()),
                ('open_close', models.CharField(max_length=100)),
                ('close_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investment_type', models.CharField(max_length=100)),
                ('trading_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('exchange', models.CharField(blank=True, max_length=100)),
                ('open_date', models.DateField()),
                ('investment_type', models.CharField(blank=True, max_length=100)),
                ('buy_or_sell', models.CharField(blank=True, max_length=100)),
                ('number', models.IntegerField()),
                ('open_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('position_break', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Position_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('buy_or_sell', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('open_avg_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('position_break', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investment_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('datetime', models.DateField()),
                ('last_statement_fund', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_charge', models.DecimalField(decimal_places=2, max_digits=12)),
                ('in_or_out', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close_break', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('position_break', models.DecimalField(decimal_places=2, max_digits=12)),
                ('usable_fund', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=12)),
                ('risk_degree', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trading_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=100)),
                ('trading_date', models.DateField()),
                ('buy_or_sell', models.CharField(max_length=100)),
                ('investment_type', models.CharField(max_length=100)),
                ('trading_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('number', models.IntegerField()),
                ('open_close', models.CharField(max_length=100)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trading_id', models.CharField(max_length=100)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAS.Statement')),
            ],
        ),
        migrations.AddField(
            model_name='position_summary',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAS.Statement'),
        ),
        migrations.AddField(
            model_name='position_detail',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAS.Statement'),
        ),
        migrations.AddField(
            model_name='close_detail',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAS.Statement'),
        ),
    ]
