# Generated by Django 2.0.6 on 2018-07-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAS', '0002_txt_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='author',
        ),
        migrations.AlterField(
            model_name='txt_data',
            name='file',
            field=models.FileField(upload_to='DAS/txt/'),
        ),
    ]
