# Generated by Django 2.0.6 on 2018-07-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DAS', '0003_auto_20180702_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='datetime',
            new_name='sta_datetime',
        ),
    ]
